### ISSUE TITLE
Ban check not working for !buy X item

### ISSUE THREAD

**Issue by joekiller** [TF2Autobot/tf2autobot#1034]
Hello a user reported their bot was reported for trading with banned users. The ban checks were enabled and said okay during the transaction.

We should check for bans prior to accepting friend requests. The banned user is 76561198393516972 however the bot seems to think it's okay
[logs.txt](https://github.com/TF2Autobot/tf2autobot/files/8120799/logs.txt)

v4.5.4, Jan 12, 4:20 pm EST
[joekillerbot3-2022-01-12.log.gz](https://github.com/TF2Autobot/tf2autobot/files/8121039/joekillerbot3-2022-01-12.log.gz)

**Comment by joekiller** [comment]
I am going to arrange for my integration3 bot to have trade bans to investigate check sufficiency.

**Comment by ZeusJunior** [comment]
Replied to the bptf thread, but I see no reason to do this when you can just hardcode a SteamID?

**Comment by joekiller** [comment]
>  you can just hardcode a SteamID

If you could elaborate a little more I'm game for trying things other than dealing with a ban in an account.

With that in mind, I'm unsure if hardcoding fail would hit the right paths. the bot seemed to think the person wasn't banned it makes me think somewhere in the detection is defective in a unintuitive way.

**Comment by joekiller** [comment]
@ZeusJunior Thanks for the suggestion. I've fixed the bug.
