### ISSUE TITLE
Bot not making listings

### ISSUE THREAD

**Issue by UteJosh** [TF2Autobot/tf2autobot#1063]
I told my bot to add an item (roboot) to its pricelist, and it wont add its but listing. It also said "prices.tf reauthorization required" in the gitbash window. Thank you for your time!

**Comment by UteJosh** [comment]
how do i fix this?

**Comment by idinium96** [comment]
Hello, sorry for the late reply.
How did you add the item? Is it through Steam chat or something else? Also, please check the value for `BPTF_ACCESS_TOKEN` and `BPTF_API_KEY` - make sure you put the correct one (your bot account, not your main account).

**Comment by UteJosh** [comment]
its ok. I set the item through steam chat, and it sent me one back saying "✅ Added "Roboot" (30675;6)💲 Buy: 36 ref | Sell: 37.66 ref🛒 Intent: bank📦 Stock: 0 | Min: 0 | Max: 1📋 Enabled: ✅🔄 Autoprice: ✅½🔄 isPartialPriced: ❌🔰 Group: all" , and i am now checking the access token

**Comment by idinium96** [comment]
If you've added other items and everything else is fine, that means your bot don't have enough pure (metals) to buy that stuff. The buy order for Roboot should've been listed in the "Archive listings".

**Comment by idinium96** [comment]
No follow-up, closing this issue.
