### ISSUE TITLE
Option to Silence update notifications.

### ISSUE THREAD

**Issue by Slips-PC** [TF2Autobot/tf2autobot#1122]
**Describe the feature you'd like**
Add an option to silence all update notifications or add some sort of control on when they are sent (i.e only for x.0.0 or x.x.0 releases.)

**Additional context**
This would be less of an issue if it weren't for the (imo) odd way updates are handled for this project. You seem to be following a VCS-style constant-update model, but with version numbers, which just seems to be an inconvenience for all parties involved. I would recommend only pushing update notifications on base version releases. Receiving a message every day because of a new update push fixing one or two schema issues is an inconvenience, and depending on the use case of the admin, even actively detrimental to the workflow (in my case, I play a lot of games on linux and due to my system configuration many games will just break if you tab out, which happens often because the bot will send me a message.)

**Comment by idinium96** [comment]
I deemed every update release as important for the bot to work properly.
If you don't like it, fork the repo and implement such feature yourself.

Also:
![image](https://user-images.githubusercontent.com/47635037/170714179-bcfbc745-80bc-4b0f-8d17-4ea030c7b96a.png)

Thank you.

**Comment by idinium96** [comment]
Good point @RobotoLev, almost forgot about it.
