### ISSUE TITLE
Add a "Strip Decal" method/setting to automatically remove decals from items when buying

### ISSUE THREAD

**Issue by Bonfire** [TF2Autobot/tf2autobot#125]
**Is your feature request related to a problem? Please describe.**
When buying items that have the ability to have a decal applied to them, sometimes your bot will purchase an item with an extremely graphics/lewd decal applied.

**Describe the feature you'd like**
I propose a setting that can be enabled/disabled by admins, that when enabled will automatically "Restore" items, removing their decal. This method could be named `stripDecal()` and placed in `TF2GC.ts`. Given the fact that decals seldom increase the value of an item, there would be no realistic loss of profit. Though it is possible (granted, probably very unlikely) that a specific decal would put off certain users from purchasing an item.

Such a feature could be expanded to not only just restore decals, but also other item attributes such as Name Tags, Description Tags, etc.

**Describe alternatives you've considered**
This is just an enhancement. The only alternative would be to not care about what decals are applied.

**Additional context**
Below is a list of items that can have the decal tool applied to them:
- Flair!
- Photo Badge
- Clan Pride
- Conscientious Objector

This is just a little idea I had. I don't know if it would actually be worth the time to implement it.

**Comment by idinium96** [comment]
Not currently available. You can request it to be added to the tf2 module: https://github.com/DoctorMcKay/node-tf2

**Comment by joekiller** [comment]
This PR has the beginning of removing labels. https://github.com/DoctorMcKay/node-tf2/pull/20
