### ISSUE TITLE
Hard code Admin ID's into bot by hand

### ISSUE THREAD

**Issue by SennaDevelopment** [TF2Autobot/tf2autobot#1259]
I'm currently having a issue with my VPS in which I'm not able to add arrays-type variables (like the admins array) to the environmental variables.

Is there any way to add the ID's by hand to the part of the bot which requests the variable from the environment variables?

If so, which file would I then need to look into and add a array with the ID's?

Thanks in advance

**Comment by idinium96** [comment]
I don't really understand what you mean, but you will need to edit the `ecosystem.json` file.
Follow these steps:
- Connect to your VPS.
- Change directory to your bot folder, by default it's "tf2autobot", so run `cd tf2autobot`
- Edit the ecosystem.json file by running `nano ecosystem.json`
- Navigate to `"ADMINS"`, and update its value to the new format:
```json
{
// From
"ADMINS":  ["SteamID"],
// To
"ADMINS": [{ "steamid": "SteamID" }],
}
```
- Close the file with Ctrl + X, Hit "Y" for Yes, and then hit Enter.
- Restart with `pm2 restart ecosystem.json --update-env && pm2 save && pm2 logs` (you can exit the logs later with Ctrl + C)
