### ISSUE TITLE
Cannot make my bot connect to steam

### ISSUE THREAD

**Issue by ScottishPan** [TF2Autobot/tf2autobot#1287]
The bot doesn't want to connect to steam. All of the steam information is correct but it keeps getting wrong steam guard codes. Latest version. Also older versions as well

**Comment by idinium96** [comment]
If you happen to set up SDA to get the secrets, and then switched to mobile, the secrets obtained from SDA will no longer be valid.

You will need to set up SDA again, get the secrets, and don't switch to mobile. Keep the SDA folder in a safe place on your PC. Make sure to not lose it, as you will need it if you want to login into your bot account on a browser, manually accept the trade, etc.

Keep in mind that you don't need to keep SDA open in the background when your bot is running.

**Comment by ScottishPan** [comment]
Things that it happened when i accidentally deleted the folder with the bot in it. I will try to set up sda again tomorrow

**Comment by ScottishPan** [comment]
I've set up SDA again but it still doesn't work. Same Too many wrong Steam Guard codes error

**Comment by ScottishPan** [comment]
Oh my god im sorry for wasting time but it didn't work because there was a "," in between the brackets and not outside them
