### ISSUE TITLE
The bot wants the selling price to be higher than the buying price but I just want it to bank craft weapons

### ISSUE THREAD

**Issue by mreverett** [TF2Autobot/tf2autobot#1294]
Is there a way to make the buying price and selling price be the same number?

**Comment by idinium96** [comment]
Why?
This is a trading bot. It's not normal to have the buying and selling prices be the same.

**Comment by mreverett** [comment]
I just want it to bank craft weapons but no one will buy them if they're selling for 0.05 ref higher than they're being bought for

**Comment by rockeyroad1415** [comment]
I don't get this reply. IF you want the bot to only buy an item and keep. Then set the intent to buy - > &intent=buy

**Comment by garaiza-93** [comment]
There is not. Reading this thread raises more questions than answers. Why are you trying to use a trading bot as a mini scraptf clone? Closing.
