### ISSUE TITLE
How can I add every single tf2 item to the bot without having to go through each one individually

### ISSUE THREAD

**Issue by mreverett** [TF2Autobot/tf2autobot#1295]
I want my bot to bank every item in existence. It would take hours to enter each item individually, so why isn't there a way to add all items like there is one to remove all items?

**Comment by SeanCole02** [comment]
Make a python script to create a pricelist, albeit I'd highly suggest against banking every item in existence as you probably don't have the listing slots to do so.

**Comment by garaiza-93** [comment]
Make a script that builds an `!addbulk` command, from SKU 1, to whatever the last SKU is now. Look at TF2's item schema for details.
I disagree with adding such a feature. A lack of listing slots, the size of the pricelist file and the slow-down that will come with it, and the horror of maintaining a pricelist like that.
This enhancement request is vague, so I'm closing this. Feel free to reopen with more details.
