### ISSUE TITLE
Bot fails to accept mobile confirmation

### ISSUE THREAD

**Issue by RacerW123** [TF2Autobot/tf2autobot#1328]
**Describe the bug**

My bot fails to accept trade offers, specifically the mobile confirmation. It then messages the user saying that the item was already traded out to another player. I do have SDA and I have auto-accept trades on.

**To Reproduce**

1. Bot sends trade offer
2. Trade offer received
3. Bot accepts trade offer
4. Bot tries to accept mobile confirmation
5. Fails

**Expected behavior**
What I expect to happen is for the bot to accept the mobile confirmation without any issues.

**Screenshots and logs**
2022-08-19 16:53:08 trade: Offer #5386060415 from **************** successfully accepted; confirmation required
2022-08-19 16:53:08 debug: Accepting mobile confirmation... {"offerId":"5386060415"}
2022-08-19 16:53:08 debug: actedOnConfirmationTimestamp 1660953188465
2022-08-19 16:53:08 debug: Offer #5386060415 from 76561199163709374 done doing action on offer
2022-08-19 16:53:08 debug: Processing next offer
2022-08-19 16:53:08 debug: Already processing offer or queue is empty
2022-08-19 16:53:08 warn: Error while trying to accept mobile confirmation on offer #5386060415:  HTTP error 429 {"code":429}
2022-08-19 16:53:08 info: Message sent to ******** (************): Error while trying to accept mobile confirmation on offer #5386060415:

Summary (offer)
• Asked: 53.66 ref (Mann Co. Supply Crate Key)
• Offered: 53.66 ref (Refined Metal x53, Reclaimed Metal x2)
──────────────────────

The offer might already get cancelled. You can check if this offer is still active by sending "!trade 5386060415

Error: HTTP error 429

Version: v5.4.1

**Comment by RacerW123** [comment]
It seems that the trades will work occasionally, but most of the time it will not. Only one trade has successfully gone through, so at that time I thought it was fixed, but as of now, many more trades have not worked.

**Comment by idinium96** [comment]
First, please make sure to not run the SDA in the background while your bot is running.

Second, Steam trading has been a lot of repeating issues lately. If you see the same thing while trying to confirm the trade on your phone, then it's an issue with Steam.

**Comment by RacerW123** [comment]
> First, please make sure to not run the SDA in the background while your bot is running.
> 
> Second, Steam trading has been a lot of repeating issues lately. If you see the same thing while trying to confirm the trade on your phone, then it's an issue with Steam.

When it first happened, I thought it was an issue because I wasn't running sda in the background. So I shouldn't be running it at all?

**Comment by garaiza-93** [comment]
You do not need to have SDA running. SDA is used to get the secret credentials when setting up the bot, and that is it.
Ensure that SDA is not running in the background. Even then, it is a Steam API issue. Nothing can be done but to wait.
This is not the bot's fault. Closing.
