### ISSUE TITLE
Bot fails to start.

### ISSUE THREAD

**Issue by CoMoLLoKKo** [TF2Autobot/tf2autobot#1341]
**Describe the bug**

When I start the bot, it gives an error.

**To Reproduce**

1. Bot starts
2. Fails

**Expected behavior**
What I expect to happen is  bot to start without any issues.

**Screenshots and logs**

2022-09-01 15:29:20 error: TF2Autobot failed to start properly, this is most likely a temporary error. 
See the log:
package.version: 5.4.1; node: v16.17.0 win32 ia32}
Stack trace:
{  message: 'connect ECONNREFUSED 185.199.108.133:443', 
  code: 'ECONNREFUSED', 
  status: undefined,  
  method: 'get',  
  url: 'https://raw.githubusercontent.com/TF2Autobot/untrusted-steam-ids/master/untrusted.min.json',  
  data: undefined
}

Version: v5.4.1

I hope I wrote this report right. If I made a mistake I'm sorry.

**Comment by carlosliam** [comment]
As the error is showing, it is a network issue, not caused by the bot itself. Check and see if the machine running the bot can connect to the internet.

**Comment by CoMoLLoKKo** [comment]
@carlosliam
2022-09-02 11:44:30 warn: Failed to get data from Github 

Yes, you're right, but this mistake happens often.
When this error comes, the bot doesn't accept incoming trades.

2022-09-02 11:49:52 error: Failed to check banned:  
 connect ECONNREFUSED 185.199.111.133:443
 {"message":"connect ECONNREFUSED 185.199.111.133:443",
"code":"ECONNREFUSED",
"method":"get",
"url":"https://raw.githubusercontent.com/TF2Autobot/untrusted-steam-ids/master/untrusted.min.json"
 }

 How can i solve this?
