### ISSUE TITLE
Loop restarting, syntax error

### ISSUE THREAD

**Issue by RacerW123** [TF2Autobot/tf2autobot#1499]
Hello, I've been using tf2autobot for a long time but recently wanted to set it up with PM2 on my server. However, I've been having some troubles. I don't know how to replicate this. I followed all the steps, I looked at all the common issues but my bot won't even start. It restarts on a loop until I kill the process. Thank you for any help!

0|tf2autobot  | /home/<user>/Desktop/tf2autobot/dist/app.js:141
0|tf2autobot  |             e['status'] = err.response?.status ?? err.status;
0|tf2autobot  |                                        ^
0|tf2autobot  | SyntaxError: Unexpected token .
0|tf2autobot  |     at Module._compile (internal/modules/cjs/loader.js:723:23)
0|tf2autobot  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
0|tf2autobot  |     at Module.load (internal/modules/cjs/loader.js:653:32)
0|tf2autobot  |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
0|tf2autobot  |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
0|tf2autobot  |     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
0|tf2autobot  |     at Module._compile (internal/modules/cjs/loader.js:778:30)
0|tf2autobot  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
0|tf2autobot  |     at Module.load (internal/modules/cjs/loader.js:653:32)
0|tf2autobot  |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
PM2           | App [tf2autobot:0] exited with code [1] via signal [SIGINT]
PM2           | App [tf2autobot:0] starting in -fork mode-
PM2           | App [tf2autobot:0] online

**Comment by carlosliam** [comment]
The current version of tf2autobot requires node version 16 or higher. Please ensure that v16 or higher is the version you have installed and running PM2.

Additionally, you can generally get help faster by reaching the community via Discord, click the link here to join: https://discord.gg/4k5tmMkXjB
