### ISSUE TITLE
Bot not is not going online when i start it

### ISSUE THREAD

**Issue by OndrejOstry** [TF2Autobot/tf2autobot#1691]
When I start the bot, its not going online, it is still offline although i start it as usual, any tips, why it isnt working?
![issue](https://github.com/TF2Autobot/tf2autobot/assets/103334311/54707541-3d7f-402a-8951-e41986e837eb)

**Comment by excellproj** [comment]
Run the bot using this command pm2 start ecosystem.json && pm2 logs and show us the logs from the console.
