### ISSUE TITLE
error while starting

### ISSUE THREAD

**Issue by GXAD** [TF2Autobot/tf2autobot#1694]
I am trying to start a bot with this command pm2 restart ecosystem.json --update-env && pm2 save && pm2 logs
![image](https://github.com/TF2Autobot/tf2autobot/assets/140894603/429a9f7a-5eaf-42ed-b988-fe1cf6400a5a)

**Comment by carloslbello** [comment]
This is a rate limiting error. Using the bot on the same machine or network as other programs accessing the Steam network (such as the Steam client itself, or web browsers accessing Steam pages) is likely to cause this issue. If this is the case, try running the bot on a separate machine, ideally on a separate network (see the VPS pages on the wiki). For additional support you can add another comment on this issue or join our Discord where you will get a quicker response [here](https://discord.gg/4k5tmMkXjB).
