### ISSUE TITLE
Cant boot up the bot

### ISSUE THREAD

**Issue by FrostTheMedic** [TF2Autobot/tf2autobot#1704]
When i try to start up the bot normally i get  the error thats on the screenshot, this happened suddenly  and i didnt do anything to cause this ive been using the bot normally.

**To Reproduce**

1. node dist/app.js
2. error

**Expected behavior**
-->  Bot boots up normally

**Screenshots and logs**
![image](https://github.com/TF2Autobot/tf2autobot/assets/96980486/4654e3d8-cd3a-46b3-b5a5-d90ea3384107)

Version: package ver. 5.9.1

**Comment by idinium96** [comment]
Please update the bot to the latest v5.10.0.

Thank you.

**Comment by FrostTheMedic** [comment]
> Please update the bot to the latest v5.10.0.
> 
> Thank you.

ah alright thanks
