### ISSUE TITLE
Custom name not working and disabled inventory sort but the bot "sorted"

### ISSUE THREAD

**Issue by robinhugy** [TF2Autobot/tf2autobot#1787]
Hi!
Tried to configurate a custom game name, but is not working.
"game": {
            "playOnlyTF2": false,
            "customName": "customBOTname"

Tried with playOnlyTF2 true and false too.

Bot sorted my inventory, but i disabled it:
"sortInventory": {
            "enable": false,
            "type": 3

Tried with type 0 too.

What can i do to use these options?

Bot version: Currently running TF2Autobot@v5.13.0

**Comment by idinium96** [comment]
Hi, may I know how you edited the options? Was it with an editor or through chat command? If with an editor, was it WinSCP internal editor?

**Comment by robinhugy** [comment]
Hi!
Generated with https://tf2autobot-easy-config.vercel.app/ and edited with notepad++

**Comment by idinium96** [comment]
I see. Does it only happen after you made the changes with Notepad++? If so, it is probably because the file was saved with a wrong encoding causing your bot to reset the options to the default one. Please check your Notepad++ settings and make sure the encoding is set to "UTF+8".

Reference: https://superuser.com/questions/292086/how-can-i-enforce-so-notepad-uses-utf-8-every-time-i-create-a-new-file

**Comment by robinhugy** [comment]
I dont check inventory after the first start of the bot, when i changed the custom game name, i realized, inventory is sorted.
Checked, no need to change it, its utf-8.

**Comment by idinium96** [comment]
Hmmm. Are you editing the options.json file while the bot is running?

**Comment by robinhugy** [comment]
No, only after it stopped

**Comment by idinium96** [comment]
Hmmm, I don't know then. I suggest you try with chat command.


![image](https://github.com/user-attachments/assets/3e7a1336-04e3-492e-92c1-3d32fc08af77)

![image](https://github.com/user-attachments/assets/629ede8f-cc53-4806-9615-884fdb5e31dc)

**Comment by idinium96** [comment]
I do still think it is an issue with your editor.

**Comment by robinhugy** [comment]
It worked with the chat command.
And i found what is the problem, my configured options file not in the right place.
I put to tf2autobot-source folder next to package.json, template.env etc
And the but generated a new options.json to tf2autobot-source\files\steamname\
Thanks for your help and your hard work on the bot :]

**Comment by idinium96** [comment]
Oh, I see. I forgot to ask about the file location. I am glad that you can find the issue.

No worries. Thank you for your patience too. :)
