### ISSUE TITLE
Add trade partner's name to bot info logs

### ISSUE THREAD

**Issue by Bonfire** [TF2Autobot/tf2autobot#198]
**Is your feature request related to a problem? Please describe.**
It is difficult to discern which trade partner the bot is currently serving when looking at the bot's logs due to trade partners being referred to by their SteamID64.

**Describe the feature you'd like**
I propose trade partner's names being added to all bot `info` logs to aid bot admins in understanding exactly which trade partner their bot is currently serving. For example, the following informational log provides very little information about who the message is being sent to: `info: Message sent to 76561198174964242: /quote ✅ Success! The trade completed successfuly.`.

**Describe alternatives you've considered**
Lookup the trade partner's SteamID64 to find exactly who the bot is trading with.

**Additional context**
The `!message` command shows the user's name that the message was sent to (Example: `info: Message sent to Bon (76561198174964242): /quote 💬 Message from the owner:  Testing`, which proves to be very useful in knowing if the message was sent to the right person. I believe adding this functionality to all relevant informational logs would help aid in debugging.

**Comment by idinium96** [comment]
This will need an extra request job in order to get the trade partner's name if he/she is not a friend of your bot. You can just open the log file in some better IDE and make it highlight the current SteamID64 that you're looking for.

I'd say this is unnecessary.

**Comment by joekiller** [comment]
Seems like this is already in buy maybe doesn't quite work?

https://github.com/TF2Autobot/tf2autobot/blob/baa1f9a5eedaddfde85a0d25796030b40c95265d/src/classes/Bot.ts#L819-L823

**Comment by idinium96** [comment]
Yeah, to me steamID is enough.

**Comment by joekiller** [comment]
@idinium96 is the friend lookup bugged though? The else should provide a name right?

**Comment by idinium96** [comment]
Only if the trade partner is a friend of your bot will get their name displayed.
