### ISSUE TITLE
Allow schema from steam api

### ISSUE THREAD

**Issue by joekiller** [TF2Autobot/tf2autobot#214]
**Is your feature request related to a problem? Please describe.**
Sometimes prices.tf is out of date with the schema or goes offline thus denying my bot the ability to add items to the pricelist.

**Describe the feature you'd like**
I'd like to use the tf2-schema-2 libaray to generate a valid schema if prices.tf is out of date or unavaliable. The code is all there dependency wise so this would be just a method to poll occasionally that referesh if needed.

This will only attempt if the steam API key is set.

**Additional context**
I'd like the enhancement to poll `api.steampowered.com/IEconItems_440/GetSchemaURL/v1` and compare the schema version listed there to the one provided by prices.tf. If prices.tf doesn't match, use steam's schema.

**Comment by idinium96** [comment]
I against adding that variable. It's already internally available.
https://github.com/idinium96/tf2autobot/blob/v1/src/classes/MyHandler.ts#L2995

**Comment by joekiller** [comment]
Thanks for the reminder. I'll update the description.

**Comment by idinium96** [comment]
I've reviewed https://github.com/TF2Autobot/node-tf2-schema-2, and I think the bot don't get schema from prices.tf and it does run auto-update: https://github.com/TF2Autobot/node-tf2-schema-2/blob/master/index.js#L123

**Comment by idinium96** [comment]
Is this still valid?
Or maybe we can just change the default value for schema manager to update? Currently, it's set to every 24 hours.
https://github.com/TF2Autobot/node-tf2-schema-2/blob/master/index.js#L21

**Comment by idinium96** [comment]
> I against adding that variable. It's already internally available.
> https://github.com/idinium96/tf2autobot/blob/v1/src/classes/MyHandler.ts#L2995

I think this is necessary in order to prevent this:
![image](https://user-images.githubusercontent.com/47635037/106236690-59d8c080-6238-11eb-850e-ef32def560b5.png)

**Comment by idinium96** [comment]
v3
