### ISSUE TITLE
Send tradeSummary messages to Steam Chat but sendAlert message to Discord 

### ISSUE THREAD

**Issue by nedim387** [TF2Autobot/tf2autobot#224]
**Describe the bug**
I don't know if this should have been reported in Features request but here is what I'd like to achive: 
I want my tradeSummary  to be sent as steam chat messages and sendAlert messages like (highTier items etc.) to discord?.. This way I will be able to be informed if the bot receives a highTier item.
Right now, if i set discordWebhook.tradeSummary.enable=false and discordWebhook.sendAlert.enable=true I get tradesummary and the alerts as steam chat

**Expected behavior**
With discordWebhook.tradeSummary.enable=false AND discordWebhook.sendAlert.enable=true , Alert messages like (highTier items etc...) should be sent to discord but regular messages about accepted trades should be sent to steam chat.

Version: 2.2.3

**Comment by idinium96** [comment]
I legit don't know why it's not working.
It should work just fine tbh.

Just make sure you set `discordWebhook.sendAlert.enable` to `true` and also make sure `discordWebhook.sendAlert.url` is not empty and filled with your Discord Webhook URL.

https://github.com/idinium96/tf2autobot/blob/c9ea8eb59951cb3aac64be8471854f413cf374e2/src/classes/MyHandler/offer/accepted/updateListings.ts#L134

**Comment by idinium96** [comment]
and also `highValue.enableHold` to `true`

**Comment by idinium96** [comment]
so is this still valid @nedim387?
