### ISSUE TITLE
Generic Unusual Buy Orders

### ISSUE THREAD

**Issue by CrustTF2** [TF2Autobot/tf2autobot#230]
**Is your feature request related to a problem? Please describe.**
No

**Describe the feature you'd like**
Working generic unusual buy orders. Example: 
![image](https://user-images.githubusercontent.com/70821166/101665292-d14d5900-3a1a-11eb-9679-865008bb46fd.png)

Have generic buy orders for unusuals accept any effect, whether it's priced or unpriced.

**Describe alternatives you've considered**

Only alternative solution is to constantly be aware of offer reviews from your bot and manually accept the trade sent, however this isn't automatic.

**Comment by joekiller** [comment]
I have looked into this and running

`!add sku=597;5&intent=buy&buy.keys=0&buy.metal=0.11&sell.metal=0&sell.keys=100` 

works fine.

![image](https://user-images.githubusercontent.com/1022919/103154264-39fb3c00-4764-11eb-9d8c-f6451ac17e74.png)

![image](https://user-images.githubusercontent.com/1022919/103154256-2d76e380-4764-11eb-90ba-efe2eca22808.png)

**Comment by joekiller** [comment]
Maybe I misunderstood. 

listing works, but you want it to accept the trade automatically right?  I guess that is different.

**Comment by idinium96** [comment]
Yes, listings fine, but it will hold to review instead of accepting the trade.
