### ISSUE TITLE
Change sortInventory type

### ISSUE THREAD

**Issue by Dex-Spirit** [TF2Autobot/tf2autobot#241]
**Describe the feature you'd like**
Option where you can choose `sortInventory` type. (by Class, by Quality, etc.)
![image](https://user-images.githubusercontent.com/61100980/102356574-0b3bd380-3fb6-11eb-9262-ef5d489e76d1.png)

**Comment by idinium96** [comment]
![image](https://user-images.githubusercontent.com/47635037/103152867-fc7bca80-47c6-11eb-8478-b107784b9ac3.png)
https://github.com/DontAskM8/node-tf2/blob/master/README.md#sortbackpacksorttype

**Comment by idinium96** [comment]
> Just note
> ![image](https://user-images.githubusercontent.com/47635037/103152867-fc7bca80-47c6-11eb-8478-b107784b9ac3.png)
> https://github.com/DontAskM8/node-tf2/blob/master/README.md#sortbackpacksorttype

This might be wrong.
![image](https://user-images.githubusercontent.com/47635037/103161100-fbbf5480-4817-11eb-975e-8c47add2ecf3.png)

* will exclude 101 and 102

**Comment by Dex-Spirit** [comment]
> > Just note
> 
> > ![image](https://user-images.githubusercontent.com/47635037/103152867-fc7bca80-47c6-11eb-8478-b107784b9ac3.png)
> 
> > https://github.com/DontAskM8/node-tf2/blob/master/README.md#sortbackpacksorttype
> 
> 
> 
> ^This might be wrong.
> 
> 
> 
> Will use this:
> 
> ![image](https://user-images.githubusercontent.com/47635037/103161100-fbbf5480-4817-11eb-975e-8c47add2ecf3.png)
> 
> 
> 
> * will exclude 101 and 102

So how to choose type `by class`?

**Comment by idinium96** [comment]
101. updated in current #258
