### ISSUE TITLE
Summarize offer does not count items properly

### ISSUE THREAD

**Issue by arik123** [TF2Autobot/tf2autobot#251]
**Describe the bug**
Summarize offer returns wrong itemCount

**To Reproduce**

1. Have some of item - in our example Scrap Metal
2. !deposit name=Scrap Metal&amount=1000
3. !checkout
3. you should see the error
⚠️ Your offer has been altered. Reason: you only have 84 Scrap Metals.
⌛ Please wait while I process your offer! You will be offered nothing for 1083 Scrap Metals.

Version: TF2Autobot@v2.3.4

**Comment by idinium96** [comment]
😲
