### ISSUE TITLE
Automatically add items that exist in bot inventory

### ISSUE THREAD

**Issue by idinium96** [TF2Autobot/tf2autobot#255]
**Is your feature request related to a problem? Please describe.**
I am too lazy.

**Describe the feature you'd like**
Automatically add items to my bot pricelist with everything that my bot has.

**Describe alternatives you've considered**
People are lazy.

**Additional context**
Run `!autoadd` to add all items by default (https://github.com/TF2Autobot/tf2autobot/wiki/What-is-the-pricelist%3F#i2---item-listing-settings-parameters), or specify, example:
`!autoadd intent=sell&max=3`

If `weaponsAsCurrency.enable` is `true`, then will exclude pure and craft weapons, if `weaponsAsCurrency.withUncraft` also true, then will also exclude uncraft weapons.

Each item addition will take about 1 second if `autoprice` is set to false (or you specify sell and buy price), else will take about 2 seconds each.

**Comment by joekiller** [comment]
I'd like it if this will add _attitional_ items that aren't on the list to the list. Then I could occasionally run `!autoadd enabled=false` to update my pricelist in prep to for going through it.

**Comment by idinium96** [comment]
> I'd like it if this will add _attitional_ items that aren't on the list to the list. Then I could occasionally run `!autoadd enabled=false` to update my pricelist in prep to for going through it.

not gonna hurt my brain to think about this.
