### ISSUE TITLE
Painted items support

### ISSUE THREAD

**Issue by Haarolean** [TF2Autobot/tf2autobot#271]
**Describe the feature you'd like**
It's really upsetting that's there's no feature to create different listings for the same items with different paint colors.
Please consider implementing such a feature 🙏🏼

**Comment by idinium96** [comment]
Yea

**Comment by idinium96** [comment]
for this, your bot will not be able to create **buy order** listings because bptf still not support it over API.

**Comment by Haarolean** [comment]
Understood. Actually having an ability to create at least *sell* listings will greatly improve the experience.

**Comment by idinium96** [comment]
# CURRENT PULL REQUEST IS BROKEN

**Comment by idinium96** [comment]
# CAN TRY NOW I GUESS

**Comment by Haarolean** [comment]
`development` branch, commit `b8ec8df`. Got these issues:

A listing has been added bot with 2 different paints for the same hat
1. The bot says current stock is 0 for listing, which is not true
2. The bot doesn't create any bptf listing for these items (probably since it thinks it has 0 of them)
I tried withdrawing and depositing these items, didn't help. 
The bot has these hats in 3 different paints, I tried to add 3rd listing for 3rd paint -- didn't help.

```
✅ Added "Killer's Kabuto (Paint: An Extraordinary Abundance of Tinge)"
💲 Buy: 20 ref | Sell: 31 ref
🛒 Intent: sell
📦 Stock: 0 | Min: 0 | Max: 1
📋 Enabled: ✅
🔄 Autoprice: ❌
📢 Promoted: ❌


✅ Added "Killer's Kabuto (Paint: Pink as Hell)"
💲 Buy: 20 ref | Sell: 35 ref
🛒 Intent: sell
📦 Stock: 0 | Min: 0 | Max: 1
📋 Enabled: ✅
🔄 Autoprice: ❌
📢 Promoted: ❌


✅ Added "Killer's Kabuto (Paint: The Bitter Taste of Defeat and Lime)"
💲 Buy: 15 ref | Sell: 24 ref
🛒 Intent: sell
📦 Stock: 0 | Min: 0 | Max: 1
📋 Enabled: ✅
🔄 Autoprice: ❌
📢 Promoted: ❌
```
![image](https://user-images.githubusercontent.com/1494347/105612137-1eb73700-5dcb-11eb-87c8-09fcc79373ee.png)

**Comment by Haarolean** [comment]
Please currently ignore the last comment I posted. TF2 API is kinda down atm, might be the issue. I'll update this comment if the issue persists.

**Comment by idinium96** [comment]
you must set `normalize.painted.our` to `false` (already stated this in the pull request note).
![image](https://user-images.githubusercontent.com/47635037/105615615-154ebe80-5e0d-11eb-905b-d4672f10c50f.png)
https://github.com/TF2Autobot/tf2autobot/pull/278

**Comment by idinium96** [comment]
Also, you did not add a listing, you only add 2 different price entries.

**Comment by Haarolean** [comment]
Sorry, I mainly read #275's notes and according to [this](https://github.com/TF2Autobot/tf2autobot/pull/275#issuecomment-761529332) comment thought that it's backward compatible (if there's no paint specified for a listing then any paint will do).

Isn't that possible to leave old entries as is and create new with paints specified? Do I have to recreate all the listings for all painted items?

Btw, wdym by 'listing' vs 'price entry'? How do I create the rest?

**Comment by idinium96** [comment]
> Isn't that possible to leave old entries as is and create new with paints specified? Do I have to recreate all the listings for all painted items?
#283 - which is a pain to implement.

> 'listing'
backpack.tf listings (buy or sell orders)

> 'price entry'
each element of an array found in your `pricelist.json` file.

> How do I create the rest?
what? items with painted? currently, there is no other option other than manually add all of them one by one.

**Comment by Haarolean** [comment]
#283 is a different suggestion.
I meant leaving previously added unpainted listings (i.e. you have a hat with 2 different paints, they're being sold for the same price on 2.x version) and setting a price per paint for new listings (manually set a price for each paint for the same hat).

I got confused by 
> Also, you did not add any listing, you only add 3 different price entries.

Tried changing normalize setting and seems like everything works fine now (unpainted listings are inactive now, but whatever). I'll ask the bot's manager to test things out and will let you know if something goes wrong. Thanks much!
