### ISSUE TITLE
Enhance key conversion rate

### ISSUE THREAD

**Issue by sumet123** [TF2Autobot/tf2autobot#272]
**Is your feature request related to a problem? Please describe.**

The current implementation use key selling price for conversion for calculating the price. Consider the following situation:
_The market (other bots on classified) is buying a key for 51 refs and selling for 52 refs - selling for more than 52 refs is almost impossible. Somehow, our autoprice price the key to buying for 51 refs and selling for 53 refs. Someone could take 1-ref item and 52 refs from the bot by paying a key - meaning the bot paying ~53 refs for a key. However, this problem shouldn't last that long because the autoprice will update the price to meet the market._

**Describe the feature you'd like**

Use different key conversion rate base on 2 scenarios:
- Use key **selling price** for conversion when the partner is **taking keys** from the bot
- Use key **buying price** for conversion when the partner is **giving keys** to the bot

This implementation is more logical, all other items use this logic for calculating the price.

**Comment by idinium96** [comment]
![image](https://user-images.githubusercontent.com/47635037/104728795-68bc6f00-5772-11eb-93f8-8356195127dc.png)

Because of this, I've canceled this implementation.

**Comment by sumet123** [comment]
> ![image](https://user-images.githubusercontent.com/47635037/104728795-68bc6f00-5772-11eb-93f8-8356195127dc.png)
> 
> Because of this, I've canceled this implementation.

That happens because the bot will convert everything (including keys) to scrap for calculating the value. All incoming offer buying the items worth more than 1 key (`sell.keys > 0`) will be declined because of invalid value (unless the partner paying with metals only)

The possible fix is to not convert the key to scrap (both actual key and the key from `buy.keys` / `sell.keys` in the item price) when calculating the value. Then using { key: number, value: number (value in scrap) } for calculating and comparing instead.

My solution takes a lot of rework on the complicated parts of the bot so it is not worth implementing just for this issue. There might be better solutions but I have no other idea for now.

**Comment by idinium96** [comment]
yes and I against your solution.

**Comment by joekiller** [comment]
@idinium96 please correct me if I'm wrong.

The intention is:

The buying rate is only applied if the key being specially bought by the bot.

The selling rate is applied if the key is being offer in exchange for an item that is for sale. 

I think this can be closed.
