### ISSUE TITLE
Auto Pricelist

### ISSUE THREAD

**Issue by TheCatDev** [TF2Autobot/tf2autobot#276]
does a script exist that automaticly add and updates all items to the pricelist?

**Comment by Bonfire** [comment]
Can you please be more descriptive?

**Comment by TheCatDev** [comment]
> Can you please be more descriptive? Do you mean a script to add every item in the game to your bot's pricelist?

Yes bcs my friend tried to buy a scattergun and it didnt worked. just a script that adds all items to the list.
