### ISSUE TITLE
Add item trade statistics

### ISSUE THREAD

**Issue by Bonfire** [TF2Autobot/tf2autobot#281]
**Is your feature request related to a problem? Please describe.**
Currently, users are unable to determine whether or not specific items are profitable, whether or not specific items buy/sell often, or view general trade data about specific items.

**Describe the feature you'd like**
I propose a new feature - we can call it `!summary`, or perhaps `!sales`, that would provide historic item trade data through Discord Webhook or Steam Chat. It would be called like so: `!summary/sales sku=459;6` or `!summary/sales name=Cosa Nostra Cap`. And it would provide users information like what is seen below:

![image](https://user-images.githubusercontent.com/5704760/105281802-efaa8680-5b7a-11eb-8ef5-88aeedd0486a.png)
_Note: This information was sourced from https://gladiator.tf/_

This would allow users to see if an item buys/sells well. If it has gone up or down over time. How many (quantity) are being bought/sold. Overall, this would provide users with more granular trade data for items, which they can then use to make informed trading decisions.

**Describe alternatives you've considered**
Using another service (like gladiator.tf) to see trade data. However, this is not pertinent to _your specific bot_, which may change things (such as not having an over-/under-cutter, having more/less capital, etc.).

**Additional context**
I believe that this feature could be implemented by either parsing the already existing `polldata.json`, or by logging item-specific trade history in a separate file, such as `history.json`.

**Comment by idinium96** [comment]
Love it, and let's also discuss the best structure for the .json files for this, and I think I like separate files better since the bot will only need to load small files at a time.
