### ISSUE TITLE
Painted Items Pricing and Logic 

### ISSUE THREAD

**Issue by rockeyroad1415** [TF2Autobot/tf2autobot#283]
**Describe the feature you'd like**
User should be able to set custom prices for different paints in the options.json file. So whenever the bot is selling a painted item, it should take the base item selling price  + the paint value  = painted item selling price. This painted item selling price should be listed on backpack.tf - the base item price should also be able to be autopriced (optional for user to choose) 

**Describe alternatives you've considered**
None. This seems like the most logical way to go about doing it. As you are "automating" the whole process. 

**Additional context**
Talking to IdiNium, he mentioned that every time a user wanted to sell a painted item, they would have to use the ! command so the bot knows what to do, in terms of item and pricing (base and paint price). This is simply too slow and increases the maintenance time users have to put in to maintain a "painted items bot". Even if users are not maintaining a "painted items bot", users will lose out on profit when their bots receive a painted item, as with the logic now, the painted item will be priced at the non-painted value.

**Comment by idinium96** [comment]
Thanks for the feature request. This might be a pain to implement.
Do you get any bounty reward for anyone who fulfills your request?

**Comment by idinium96** [comment]
Could you please at least provide the default value for each paint?

example:
A Color Similar to Slate: 0 keys, 30 ref.

**Comment by rockeyroad1415** [comment]
Can you please clarify what do you mean when you say bounty reward?

I am not a painted items seller, so I guess you can just have a default value, and if the user doesn't wanna add a surcharge for painted items it can be, 0 keys and 0 ref added. But yes i can give a couple examples: 
![image](https://user-images.githubusercontent.com/47135262/105934652-b905cc00-60a4-11eb-871a-5576769d292f.png)

see if this helps. 
also another consideration, i see that your project you like to have the options.json file as condensed as possible. So by including the names of all the paints, it would mean that the file might get cluttered. So another consideration would be to use, another json file, named "paintedvalues" where the bot, adds all the paint names, with default 0 keys and 0 ref (buy and sell), and then the user can edit the values as needed. 

To clarify, it should be something like this (or along the same track): 
```
{
 Color Similar to Slate:
Buying: {
keys: 0,
ref: 0},
Selling: {
keys: 0,
ref: 10}
}
```
excuse the formatting and all~ did it real quick. This is so that the bot knows how much to add to its pricing when buying and selling!
If any questions lemme know. Happy to help.
