### ISSUE TITLE
Better Pricing

### ISSUE THREAD

**Issue by rockeyroad1415** [TF2Autobot/tf2autobot#284]
**Is your feature request related to a problem? Please describe.**
Yes, TF2AutoBot will sell items for less than the price the item was bought at. Making the whole gaining 0.11 ref + profit logic redundant.

**Describe the feature you'd like**
An option for users to choose how often the items in their backpack which they are selling get re-priced. Items which are in the pricelist, but the bot doesn't have (buying), should be updated frequently, so that the most competitive prices are offered. 
For example:
- If stock = 1 or more, bot doesnt update the selling price, only the buying price. 
- If stock = 0, bot updates both the buying and selling prices
  o Safe guard should be added here: if buying price = selling price of other bot users (simple bp.tf check) then buying price - 0.11 ref = new buying price. But the selling price stays same with the market (other bots). 

After 7 days (or whatever the user chooses, can be a entry in options.json?) the whole pricelist stock = 1 or more AND 0 gets updated with new prices. So that the bots inventory turnover remains high. 

**Describe alternatives you've considered**
Manual pricing but that's yuck. 

**Additional context**
The above allows for profit to be generated in majority if not all of the trades the bot conducts. Not more loss on sales. As prices.tf has cycles in the pricing of its items, by having the above allows for users and their bots to control more of the pricing cycle.

**Comment by idinium96** [comment]
What if when the bot updating the price, selling <= buying price? Afaik, the bot will fail to update the prices because the validator rejected it (since the selling price must be more than buying price).

**Comment by rockeyroad1415** [comment]
Yup! if thats the case, then you would wanna make the bot price the sell side of things, buy keys = 999 and sell keys = 999 - and then in your listing code, have a if condition that, if the sell price is 999 of both keys and ref, then the bot ignores to list the item. And then the bot after sometime, or in its normal pricing cycle will re-price everything which has stock=0 and prices having 999 keys and ref. 
If you have more questions lemme know! Happy to help :)

**Comment by idinium96** [comment]
Thanks for the reply, and sorry for the late response.
I found your method a bit difficult to implement.

The part when the bot determines whether the bot already has that item is easy to implement in my opinion, but for your info, when the bot starts, it will first get the entire pricelist from prices.tf and update the prices if the time recorded on an item in the pricelist is too old (`pricelist.priceAge.maxInSeconds` option). At this moment, the bot is still not connected to Steam and thus getting info about how many the bot has of that particular item will be impossible during this execution.

Not sure adding something to the pricelist entry will be a good idea or not.

**Comment by idinium96** [comment]
But, I think I can just change the order. will test it later I guess.

**Comment by rockeyroad1415** [comment]
yup exactly! can change the order when the check is implemented, can be after the ready signal is given by the bot. Or another idea for the thought, you can run that check on a timer, or after certain number of trades (might be better to stick with timer) but still!

**Comment by idinium96** [comment]
I might let others think about it.

**Comment by idinium96** [comment]
you can start a discussion in #technology channel in discord to kinda figure out how to make this possible if you want to.
