### ISSUE TITLE
Pure count wasn't updated

### ISSUE THREAD

**Issue by Haarolean** [TF2Autobot/tf2autobot#285]
**Describe the bug**
For some reason bot didn't update pure count after a trade.

**To Reproduce**

No idea how to reproduce this.

**Screenshots and logs**
![image](https://user-images.githubusercontent.com/1494347/105606582-5d3cf980-5dab-11eb-8cca-a2a137e2b325.png)

**Additional context**
`!pure` reported the same (wrong) amount. I withdrew 1 ref and it got fixed in the next message.
![image](https://user-images.githubusercontent.com/1494347/105606707-008e0e80-5dac-11eb-92bd-0356446b3bd8.png)

Version: 2.3.5

**Comment by idinium96** [comment]
It can happen when multiple trades occurred at the same time, so this won't be fixed.

**Comment by Haarolean** [comment]
@idinium96 there were no simultaneously accepted trades at the same time, there's 10 mins difference between these 2 trades.

**Comment by idinium96** [comment]
Ok, then this is likely rare, and it will be automatically fixed on the next trade summary.
