### ISSUE TITLE
What is a Prices TF API?

### ISSUE THREAD

**Issue by BananinhaWR** [TF2Autobot/tf2autobot#289]
I don't know what is a Prices TF API
I don't know if it's obligatory to fill the **PRICESTF_API_TOKEN=""** , the instructions guide don't seem to say anything about what the option does. If it is obligatory, how do I do that?

Version: 2.3.8

**Comment by BananinhaWR** [comment]
> 
> 
> I don't know what is a Prices TF API
> I don't know if it's obligatory to fill the **PRICESTF_API_TOKEN=""** , the instructions guide don't seem to say anything about what the option does. If it is obligatory, how do I do that?
> 
> Version: 2.3.8

**Comment by BananinhaWR** [comment]
Srr, ended up closing it

**Comment by idinium96** [comment]
It's not in required things https://github.com/TF2Autobot/tf2autobot/wiki/Configuring-the-bot-(v2)#required-variables

Thus, it's not required. Just leave it like that.

**Comment by BananinhaWR** [comment]
Thx, do you know what this means then?
Is it really a temporary error or and I doing something wrong?
![image](https://user-images.githubusercontent.com/46030774/106210805-4da42300-61a6-11eb-9f46-becc4ccd74ef.png)

**Comment by idinium96** [comment]
like I said, just leave it as is.
`PRICESTF_API_TOKEN=""`

if you put anything in that empty string (`""`), then that will happen.
