### ISSUE TITLE
What's wrong with this !add code? !add sku=31181;6;buy.metal=2.33;sell.metal=2.77

### ISSUE THREAD

**Issue by BananinhaWR** [TF2Autobot/tf2autobot#290]
I want this code to be to the Sniper **Killing Tree**
I want my bot to buy it for _2.33_ ref and sell for _2.77_ ref
The **SKU** of the item is _31181;6_
The bot said this:
![image](https://user-images.githubusercontent.com/46030774/106291365-4c1c3e80-622a-11eb-8c41-c22223d076a5.png)
So which properties 

are missing? Or am I just writing something wrong?

**Comment by idinium96** [comment]
You missed `&` in between parameters.
Should be: `!add sku=31181;6&buy.metal=2.33&sell.metal=2.77`

Please ask in #help channel on TF2Autobot Discord Server. Closing.
Thanks.
