### ISSUE TITLE
Change the way profits work in the stats command to not count admin trades

### ISSUE THREAD

**Issue by k4zzy** [TF2Autobot/tf2autobot#299]
**Is your feature request related to a problem? Please describe.**

Not sure if its a bug or not, profits count items that were sold but not bought.

**Describe the feature you'd like**

The profits should not include items given to by an admin (or there should be a separate section for this kind of profit).
For example: I give my bot an item to sell for 50 keys. The item sells. This 50 keys should not count as profit made by the bot.
Another example: My bot buys an item for 40 keys, then sells the item for 50 keys. This should count as 10 keys profit made by the bot.

**Describe alternatives you've considered**

Manually keep track of items I give to my bot and what they sell for, but I'm lazy :)

**Comment by arik123** [comment]
How would you suggest, for the bot to set the initial price of the item that comes from admin trades ? Because the main problem here is that, we dont have any price for the item in logs, so it gets set to 0.

**Comment by ebhammond** [comment]
Can the initial price be set after the item has been sold? If the buy price is set equal to the price it sold for, it wouldn't be marked as profit.

**Comment by idinium96** [comment]
I've reviewed the scripts in `src/lib/tools/profit.ts`, and I find that anything sold without bought is not considered as full profit.

**Comment by idinium96** [comment]
and ignore trades from admins already implemented in `v3.3.0`, so I might close this issue.
