### ISSUE TITLE
Modifying pricelist entry group to "all" does not display a change

### ISSUE THREAD

**Issue by Bonfire** [TF2Autobot/tf2autobot#324]
**Describe the bug**
When updating a pricelist entry's group from anything to `all`, the bot does not show the group being changed.

**To Reproduce**

1. Change a pricelist entry's group to something
2. Change the same pricelist entry's group to `all`
3. Verify that while an update message was shown, the group change is not displayed

**Expected behavior**
The update message should have an entry for `🔰 Group: <PREVIOUS GROUP> → all` like it does for `🔰 Group: all → <NEW GROUP>`. This may be done on purpose, and if it is I believe that it should be modified

**Screenshots and logs**
![image](https://user-images.githubusercontent.com/5704760/107463105-7ecc0e00-6b2b-11eb-81d1-6cea98fcf520.png)

**Additional context**
N/A

Version: TF2Autobot@v3.2.5

**Comment by idinium96** [comment]
It's intended.
https://github.com/TF2Autobot/tf2autobot/blob/39cc13e26c310404e7cc412c8e8130bbbef06519/src/classes/Commands/functions/pricelistManager.ts#L368

**Comment by Bonfire** [comment]
Then shall we mark this as an enhancement? I believe the change should be shown.

**Comment by idinium96** [comment]
up to you. much better if you do commit and create a pull request for it 😇

**Comment by Bonfire** [comment]
> up to you. much better if you do commit and create a pull request for it 😇

Can do 😛
