### ISSUE TITLE
Invalid item quantity in deposits if partner does not have item

### ISSUE THREAD

**Issue by Bonfire** [TF2Autobot/tf2autobot#326]
**Describe the bug**
Currently, if you attempt to deposit an invalid quantity of an item you do not have, the bot will attempt to process an offer with one less of the item and error.

**To Reproduce**

1. Deposit some quantity of an item you do not have
2. Send the `!checkout` command to execute the trade
3. Verify that the bot mentions you do not have the item, and offers to create a trade with one less of the item
4. Verify that the bot errors out when attempting to create the trade

**Expected behavior**
If possible, the bot should attempt to recognize that the user does not have the item. If not possible, the bot should at least not attempt to create a trade with one less of the quantity specified.

**Screenshots and logs**
![image](https://user-images.githubusercontent.com/5704760/107464333-12064300-6b2e-11eb-86b6-a3e2ea1277fa.png)
An example where my account does not have any refined metal, and I asked to deposit 5. The bot says it cannot find any, and attempts to send an offer for 4 refined metal.

**Additional context**
N/A

Version: TF2Autobot@v3.2.5

**Comment by joekiller** [comment]
Thanks for this clear report
