### ISSUE TITLE
Generic Unusual Buy Orders not working.

### ISSUE THREAD

**Issue by Dormeo** [TF2Autobot/tf2autobot#340]
**Describe the bug**

Generic Unusual Buy Orders not working. Let's take Unusual Tyrantium Helmet as an example:  price list contains buy order of Unusual Tyrantium Helmet for 7 keys and 7 refs * https://imgur.com/jk2v6pG * by the Generic unusuals function order this should mean that the bot accepts any effects at this price, but when trying to sell to my bot a cap with any effect, it shows an overstock message "https://imgur.com/HLuK25m" that he buys such a cap in a number of 0. I tested it with other caps in the same way. When I disable  overstock check,  bot accepts this header, but ignores my price, if I have a price of 7 keys and 7 refs, then  bot accepted trade of 7 keys and 15 refs

**Expected behavior**

Accept caps of any effect at a fixed price, with one lot with the prefix "Unusual"

**Screenshots and logs**
https://imgur.com/jk2v6pG
https://imgur.com/HLuK25m

Version: 3

**Comment by joekiller** [comment]
@Dormeo Could you post them logs from when the incident occurred?

**Comment by Dormeo** [comment]
> @Dormeo Could you post them logs from when the incident occurred?

first 06.02.2021 Steaming Pugilist's Protector
seccond 08.02.2021 Nuts n' Bolts Head Of Defense   and any.

**Comment by Dormeo** [comment]
I would like to add one more thing, in v.2, for example, if my price for a gen unusual is 6 keys, and about  price. TF it is 6.1+ key, bot accepted such hat automatically, so if you cannot find  problem, I think it would be better return the old system, where at least sometimes the bot itself accepted hats.

**Comment by idinium96** [comment]
Maybe we should make the `amountCanTrade` always be 0 @joekiller? Since people that want to use Generic Buy orders usually do not care about what unusual they will receive. 🤔🤔🤔

**Comment by Dormeo** [comment]
> Maybe we should make the `amountCanTrade` always be 0 @joekiller? Since people that want to use Generic Buy orders usually do not care about what unusual they will receive. 🤔🤔🤔

Please pay attention, as I already said, if you disable overstock, bot will recognize price of effect, and not one my b/o price. It doesn't matter to me how many bot will buy them,  fact that the bot ignores my price when it turns off overstock is important to me.

**Comment by joekiller** [comment]
Hello., I have been very busy so I apologise for the slow response. I'll try to run this through the test suite

**Comment by joekiller** [comment]
@Dormeo I'm trying to look at this and yes I can replicated it. In the future when we ask for logs they are located, as the issue template mentions, in `tf2autobot\logs`. The logs help during diagnosis to confirm we are fixing the correct problem.

**Comment by joekiller** [comment]
@idinium96 what was you intention of changing this line from just `which === 'their'` to the complex compairsion of now https://github.com/TF2Autobot/tf2autobot/blob/d2fffdeb32a4aee3f56e876997406388e5a14cd6/src/classes/MyHandler/MyHandler.ts#L1086?

Because there is a sku for the order the match === null is false which sets the amountCanTrade to generics = false so that's why it doesn't think it can trade.

I'd just change it back to `which === 'their'` unless I'm missing something. that should fix it.

**Comment by idinium96** [comment]
Oh right, My intention was to not mix other things (non-unusual stuff), but I guess I am wrong. The condition for `match === null` will always `false` since it's already in `match !== null`.
