### ISSUE TITLE
Adding total profit per item in the !itemstats command.

### ISSUE THREAD

**Issue by SachinVenugopalan30** [TF2Autobot/tf2autobot#356]
When sending the `!itemstats` command, after pulling stats, the bot can calculate total price in buys and total price in sales, after which a comparison can be made to see the net profit made off that specific item.

Example: https://gyazo.com/43ef7aeb198ab9eeaccee1573929a556
23 bought, 22 sold(can take take 22 bought and 22 sold for calculating the net profit)

Total price of all buys: **22 keys + 14.6 keys** _(746.22 ref converted to keys using current keyrate)_ = **36.6 keys**
Total price of all sales: **22 keys + ~15 keys** _(764 ref converted to keys using current keyrate)_ = **37 keys**

Net profit = 37 - 36.6 = 0.4 keys for this item.
Net loss can also be shown in a similar fashion.

This way, more information can be given to the bot owner on a per-item level to see which items have more sales and which items provide them with the most profit.

Users that are whitelisted (ITEM_STATS_WHITELIST) can only see stats and not the profit portion. Only ADMINS can see this statistic.

**Comment by idinium96** [comment]
so these total sales are just within that past 30 days right?

**Comment by idinium96** [comment]
I will make it only past 30 days.

**Comment by idinium96** [comment]
![image](https://user-images.githubusercontent.com/47635037/108603640-15c67f00-73e4-11eb-861d-02c543a409e4.png)

**Comment by SachinVenugopalan30** [comment]
Past 30 days is perfect for this.
