### ISSUE TITLE
Setting the Discord Webhook to mention owner (for trade summaries) as true doesn't work

### ISSUE THREAD

**Issue by CrustTF2** [TF2Autobot/tf2autobot#443]
Basically the title. The mentionOwner setting for the trade summary discord webhook doesn't work.

This is what my current options file looks like for the section: https://i.imgur.com/3gLGEcn.png
This is what my discord webhook shows when those options are set: https://i.imgur.com/T3vIe9H.png
The mentionOwner setting still works for offer review though.

Minor bug, but still a bug.

**Comment by idinium96** [comment]
Not a bug. You must at least put something in the `.itemSkus` array. To mention all, put `[";"]` so all sku will be mentioned.
