### ISSUE TITLE
Bot lists craft weapons for sale

### ISSUE THREAD

**Issue by arik123** [TF2Autobot/tf2autobot#449]
**Describe the bug**
When bot recieves weapons trough tradeoffers, it lists them for sale instead of crafting them.

**To Reproduce**
1. Have a listing
2. Use weapons to pay instead of currencies
3. Observe

**Expected behavior**
Bot will craft weapons together if possible or it will just keep them.

Version: 3.6.5

**Comment by idinium96** [comment]
Unable to reproduce.
v3.6.5

![image](https://user-images.githubusercontent.com/47635037/110685086-e05dc600-8218-11eb-9881-12712bb820b5.png)
![image](https://user-images.githubusercontent.com/47635037/110685098-e2c02000-8218-11eb-89bc-646851d4def3.png)

**Comment by arik123** [comment]
Maybe this happend on 3.6.4 and I did not notice it, will keep looking, and if it happens again, will send logs.

**Comment by idinium96** [comment]
Alright.

**Comment by idinium96** [comment]
My bot `options.miscSettings` settings:
![image](https://user-images.githubusercontent.com/47635037/110688647-c7571400-821c-11eb-8ec9-4f0e9fe8ec40.png)
