### ISSUE TITLE
Plan for v4

### ISSUE THREAD

**Issue by idinium96** [TF2Autobot/tf2autobot#450]
✨ :
- [x] Support counter offer for `🟥_INVALID_VALUE` offers.
- [x] Refactor pricelist.json - `Array` → `Object`.
    - [x] If we do this, that means need another script to convert the current pricelist into the new one.
- [x] Refactor `bptf-listings-2` to use like @Hhanuska 's [forked version](https://github.com/Hhanuska/node-bptf-listings) (already implemented on v3.8.1).
- [ ] Working integration tf2autobot ⇆ tf2autobot-gui with IPC (currently in progress).
- [ ] Send Steam ID to *TF2Autobot API so the bot will be listed on [Autobot.tf](https://autobot.tf/) main page ~~(paid version?)~~.
- [ ] ~~Send trade summary to *TF2Autobot API so it will be shown in [Autobot.tf](https://autobot.tf/) trades page ~~(worth it?)~~.~~
- [ ] Database?
- [ ] `!donateAutobot` command - will send to TF2Autobot donation bot (or better `!donateIdiNium`?)
- [ ] ~~Do not use `polldata.json` to store offer info (store it in individual files - worth it and is it better?)~~
- [ ] Refactor `options.json` - separate into multiple files

\* \- not yet exist

Deadline: N/A

**Comment by rennokki** [comment]
Perhaps some external database drivers like Redis for storing poll data are going to be nice?

**Comment by idinium96** [comment]
> Perhaps some external database drivers like Redis for storing poll data are going to be nice?

Yes, that sounds good, but I wonder if it's much better. It will still load the entire thing, isn't it?

**Comment by rennokki** [comment]
> > Perhaps some external database drivers like Redis for storing poll data are going to be nice?
> 
> Yes, that sounds good, but I wonder if it's much better. It will still load the entire thing, isn't it?

You're going to set keys based on the timestamp with values accordingly.

**Comment by idinium96** [comment]
The current keys in `offerData` are `offerID`, not timestamp, but yeah kinda understand that. I don't have any experience with an external database so might be difficult for me for now.

**Comment by rennokki** [comment]
I can take some insight over this and come up with a practical solution if that helps.

**Comment by idinium96** [comment]
That should be helpful. I will create a `v4-dev` branch so anyone can create a pull request to that branch for anything related to the v4 plan.

**Comment by arik123** [comment]
> * [ ]  Send Steam ID to *TF2Autobot API so the bot will be listed on [Autobot.tf](https://autobot.tf/) main page (paid version?).
> * [ ]  Send trade summary to *TF2Autobot API so it will be shown in [Autobot.tf](https://autobot.tf/) trades page (worth it?).

I would suggest going with IDs only for now.

> * [ ]  Database?

Sqlite ?

> * [ ]  Do not use `polldata.json` to store offer info (store it in individual files - worth it and is it better?)

I dont see any problems with polldata right now ? But might be possible to store it in the database as well.

**Comment by idinium96** [comment]
right. Thanks for the opinion.

> I don't see any problems with polldata right now? But might be possible to store it in the database as well.

yea true, but idk if it's good to keep it growing. My bot polldata size currently at about 10 MB, and it's totally fine, but idk what will happen if the size went to 100 MB later. But I guess for now let just keep it as it.

**Comment by idinium96** [comment]
> Sqlite?

Maybe. Still haven't look at how it works and not sure if it's worth the time doing it. Maybe it's worth it so I don't need to track my bot trades every single day anymore.

**Comment by idinium96** [comment]
And I am not so sure if refactoring the pricelist will help improve the performance at all since I guess this method will be broken or might use a harder approach to make it work:
https://github.com/TF2Autobot/tf2autobot/blob/master/src/classes/Pricelist.ts#L242

And also this
https://github.com/TF2Autobot/tf2autobot/blob/master/src/classes/Listings.ts#L380-L414

🤷‍♂️
