### ISSUE TITLE
Unusuals: 🟦_OVERSTOCKED while stock < max

### ISSUE THREAD

**Issue by Breeezze** [TF2Autobot/tf2autobot#457]
**Describe the bug**
Bot holds correct trade offers for review with reason `🟦_OVERSTOCKED`, while current stock < max.
This only happens with Unusuals, and only when there are several of the same item with different effects in the backpack.
For example, when:
- I am buying Massed Flies Dread Knot for 6 keys
- My current stock for this item is 0
- My max stock for this item is 2
- I currently own > 2 Unusual Dread Knots with different effects

This bug only happens on received trade offers.
Everything works as intended when seller trades via chat message.

**To Reproduce**

1. Create buy order for Unusual item with effect [X] and set maximum stock to [N]. _(User can choose X & N)_
2. Have less than [N] of said item with effect [X] available in backpack.
3. Have more than [N] of said item with different effects available in backpack.
4. Wait for seller to send a correct trade offer to the bot containing Unusual item with effect [X].
5. Bot will mark offer as `🟦_OVERSTOCKED` and hold the trade for manual review.

**Expected behavior**
Bot accepts correct trade offers containing Unusual items when stock < max.

**Screenshots and logs**
Trade below shows current stock = 0 and max stock = 2 for the Infernal Smoke Bad Pipes, 
yet the offer is marked as `🟦_OVERSTOCKED`.
<img src=https://user-images.githubusercontent.com/24300035/110855692-fde16d00-82b6-11eb-87aa-97ce3dbcb230.jpg width="300"/>

Bad Pipes with different effects available in the backpack.
<img src=https://user-images.githubusercontent.com/24300035/110856639-30d83080-82b8-11eb-8d24-1a705f1bdc90.png width="500"/>

Version: 
3.6.5

**Comment by idinium96** [comment]
Thanks for the report. We will look into it.

**Comment by joekiller** [comment]
Thanks for the details I can replicate the issue.

**Comment by idinium96** [comment]
I am pretty such this case is the same as the one my bot experiencing during v3 development. I don't buy any unusual right now so I don't know this thing still exist.

the log files I sent in the `#v3-beta-tester` and `#contributors` channel might help.
`#contributors`:
https://discord.com/channels/664971400678998016/745410459212972173/797355434263838760
https://discord.com/channels/664971400678998016/745410459212972173/798713423130525776
https://discord.com/channels/664971400678998016/745410459212972173/800620712741175316

`#v3-beta-tester`
https://discord.com/channels/664971400678998016/801610351245787156/802344313748193350
