### ISSUE TITLE
Buy listings for killstreak kit are created for wrong item

### ISSUE THREAD

**Issue by Eranikid** [TF2Autobot/tf2autobot#474]
**Describe the bug**
Bot creates `Non-Craftable Killstreak <ITEM> Kit` when selling items, which is correct, but for some reason, when buying items it creates `Non-Craftable <ITEM> Kit`, which incorrect (see missing `Killstreak` in item name)

**To Reproduce**

1. In your bot inventory have some scrap and 1 killstreak kit (for ex. Huo-Lang Heater, `sku=6527;6;uncraftable;kt-1;td-811`)
2. Issue command `!add sku=6527;6;uncraftable;kt-1;td-811&max=2&sell.metal=50&buy.metal=0.11`. Now bot must create 1 sell listing and 1 buy listing
3. Go to backpack.tf and search for listings for Huo-Lang Heater KS kit:
    3.1. Go to Trading -> Classified Listings
    3.2. Click on `...` to open advanced search window
    3.3. Put "Huo-Lang Heater" in textbox
    3.4. In dropdown, select "Find recipes where the output item is used on this item"
    3.5. In Killstreaker section select Standard Killstreak Tier
    3.6. Press confirm
4. Observe that there is a sell listing from your bot
5. Observe that there is no buy listing from your bot
6. Go to your bot profile, and check his listings, observe that he has valid `Non-Craftable Killstreak Huo-Lang Heater Kit` sell listing, but he has invalid `Non-Craftable Huo-Lang Heater Kit` buy listing

**Expected behavior**
Bot creates valid `Non-Craftable Killstreak Huo-Lang Heater Kit` buy listing, which will be visible to people searching for buyers of their killstreak kits

**Screenshots and logs**
```
{"message":"Message from Hierophant Green (76561199059666181): !add sku=6527;6;uncraftable;kt-1;td-811&max=2&sell.metal=40&buy.metal=0.11","level":"info","timestamp":"2021-03-18T10:54:22.870Z"}
{"message":"Message sent to Hierophant Green (76561199059666181): ✅ Added \"Non-Craftable Killstreak Huo-Long Heater Kit\" (6527;6;uncraftable;kt-1;td-811)\n💲 Buy: 0.11 ref | Sell: 40 ref\n🛒 Intent: bank\n📦 Stock: 1 | Min: 0 | Max: 2\n📋 Enabled: ✅\n🔄 Autoprice: ❌\n🔰 Group: all","level":"info","timestamp":"2021-03-18T10:54:22.874Z"}
{"message":"6527;6;uncraftable;kt-1;td-811 updated","level":"debug","timestamp":"2021-03-18T10:54:22.876Z"}
{"message":"Checking 6527;6;uncraftable;kt-1;td-811...","level":"debug","timestamp":"2021-03-18T10:54:22.876Z"}
{"message":"We have no buy order and we can buy more items, create buy listing.","level":"debug","timestamp":"2021-03-18T10:54:22.892Z"}
{"message":"We have no sell order and we can sell items, create sell listing.","level":"debug","timestamp":"2021-03-18T10:54:22.893Z"}

```
![image](https://user-images.githubusercontent.com/8256473/111625519-f9a8d880-87fd-11eb-9bff-d5bbf6ee9c54.png)

Version: 3.6.5

**Comment by Eranikid** [comment]
@idinium96 I saw you comment with this code on previous issue
https://github.com/TF2Autobot/tf2autobot/blob/4081e2af0ed4591e93bd443e4b2e8f5131fbc2db/src/lib/extend/item/getSKU.ts#L346-L372

Is that list comperhensive? Where can I find correct SKU for, for ex., stock Flame thrower?

**Comment by idinium96** [comment]
After some short investigation, yeah the word "Killstreak" is missing.
I will fix it in the next update. Thanks.

> Is that list comperhensive? Where can I find correct SKU for, for ex., stock Flame thrower?
That's only for (Basic) Killstreak Kit. All others can refer to the wiki ([click here](https://github.com/TF2Autobot/tf2autobot/wiki/Item-Identifying-parameters#322---sku-parameter)) on how to obtain it, or you can use my bot (which currently in the testing phase): https://steamcommunity.com/id/IdiNium-Asuna/

Add her and send `!sku <Item name>` to get the sku for an item.

**Comment by Eranikid** [comment]
Also worth noting, that I can see some bots buying KS kits, some of them are gladiator.tf, but pretty sure that at least some are tf2autobot

**Comment by idinium96** [comment]
ok

**Comment by idinium96** [comment]
https://github.com/TF2Autobot/tf2autobot/releases/tag/v3.6.8
