### ISSUE TITLE
Error with Negative Profit

### ISSUE THREAD

**Issue by RonSwanson2** [TF2Autobot/tf2autobot#486]
When givePrice is disabled and unknown incoming offers that are not part of the bots pricelist are received it shows the price as "0 keys, 0 ref". This is proper. However if the invalid offer gets accepted and the item becomes part of the pricelist and furthers to still dissipate the amount of value that item/items had. It shows as a negative profit after doing !stats after that invalid offer trade.

1. givePrice=false
2. autoAcceptOverpay=true
3. Offer a trade with multiple items where one of those items is not part of the pricelist.
4. !stats
5. Check if profit became negative.

I expected that the bot recognized that the items were not actually worth "0 keys, 0 ref" and understood that I have profited from that invalid trade.
The image below is !stats before the invalid offer trade.
![image](https://user-images.githubusercontent.com/76535229/111999578-805a0000-8af3-11eb-8a99-8aae50a65550.png)
![image](https://user-images.githubusercontent.com/76535229/111933148-43f7b700-8a95-11eb-8103-07f1684e80ed.png)
![image](https://user-images.githubusercontent.com/76535229/111933171-4c4ff200-8a95-11eb-8ddd-bd06bc520ec0.png)

Version: 3.7.0

**Comment by idinium96** [comment]
Thanks for the report

**Comment by RonSwanson2** [comment]
> Thanks for the report

No problem. I want the github contributor role for doing nothing now lmao
