### ISSUE TITLE
Bot reverting to autopricing for selling and item when buy.keys is not set in !update command

### ISSUE THREAD

**Issue by SachinVenugopalan30** [TF2Autobot/tf2autobot#488]
**Describe the bug**
Any high value item that is according to the owner's settings will be disabled. If the user wishes to set a manual price but does not set `buy.keys` while running the `!update sku=<>&enabled=true` command, the bot will revert to autopricing after a while instead of using the `sell.keys` or `sell.metal` that was manually set by the owner.

**To Reproduce**

1. Receive a high-value item from a trade(say an item with high value parts/paint/killstreaker/spell)
2. Send the `!update` command as mentioned earlier but **DO NOT** add the `buy.keys/buy.metal` part. So your update command will look something like `!update sku=30998;6&enabled=true&sell.keys=25`
3. Wait. Unsure of when exactly will the bot revert to autopricing.

**Expected behavior**
Bot should maintain the manual price until the item has sold.

**Screenshots and logs**
Receiving and setting the item to sell at a price set by the owner:
![image](https://user-images.githubusercontent.com/31774135/111990865-b15d2380-8b39-11eb-95ed-b50e40f56feb.png)

![image](https://user-images.githubusercontent.com/31774135/111990883-b5894100-8b39-11eb-88c0-cd9884dd05c2.png)

![image](https://user-images.githubusercontent.com/31774135/111990923-bcb04f00-8b39-11eb-9605-89ff9adb4237.png)

As you can see from the image above, in the `_ITEM_PRICES` segment, even though I set `sell.keys` to 2, the bot reverted to 1 key, but pricing method is still 'manual'. Time span between setting the price and the bot selling the item for that price was a little above 24 hours, although this depends on the item being sold.

Meanwhile, if you have set `buy.keys` in the same update message, the bot will not revert to autopricing.
![image](https://user-images.githubusercontent.com/31774135/111991436-5841bf80-8b3a-11eb-8372-d626c1d57d69.png)

![image](https://user-images.githubusercontent.com/31774135/111991451-5aa41980-8b3a-11eb-8870-d9ba1a1dddc7.png)

When I sent `!update sku=30599;6&sell.keys=2&buy.metal=1`, the bot did not revert to autopricing.

![image](https://user-images.githubusercontent.com/31774135/111991625-86270400-8b3a-11eb-9a9a-ceec5a0fa9b9.png)

Version: v3.6.5.

**Comment by idinium96** [comment]
Thanks for the report.
