### ISSUE TITLE
Pricechecker is preventing the bot from finishing startup when the number of listings is high

### ISSUE THREAD

**Issue by Braithirne** [TF2Autobot/tf2autobot#517]
**Describe the bug**

When the number of listings the bot has is high enough, the bot is softlocked by the price checker when it starts, preventing it from finishing startup.

**To Reproduce**

1. Have a high number of listings
2. Attempt to start bot

**Expected behavior**

Pricechecker should run AFTER bot is fully finished starting up.

**Screenshots and logs**

<a href="https://gyazo.com/cd20370146034c6f9c7e3dea1a488231"><img src="https://i.gyazo.com/cd20370146034c6f9c7e3dea1a488231.png" alt="Image from Gyazo" width="716"/></a>
<a href="https://gyazo.com/17e467ccc69eef51cd2bf15e84113720"><img src="https://i.gyazo.com/17e467ccc69eef51cd2bf15e84113720.png" alt="Image from Gyazo" width="967"/></a>
<a href="https://gyazo.com/2e394f96ef4ae01211e9ef5b14f10cd9"><img src="https://i.gyazo.com/2e394f96ef4ae01211e9ef5b14f10cd9.png" alt="Image from Gyazo" width="306"/></a>

**Additional context**

The number of listings Bender is trying to go through is 10,000 or so. It works if most of the listings are disabled, but I don't have a number for when the issue starts.

Version:

**Comment by Braithirne** [comment]
The screenshots show a fresh restart but this issue persists for hours. Its not the listings thats the problem, it will finish listing but still won't fully start up.

**Comment by idinium96** [comment]
Alright. I Will have a look at that, probably @joekiller can help with this issue.

**Comment by idinium96** [comment]
This problem was caused by these changes:
https://github.com/TF2Autobot/tf2autobot/compare/v3.6.5...master#diff-593fd309b223906a7c2e488767eb27f311d1c07304347be8cafe21225867d3c6L509-R517

🤯
