### ISSUE TITLE
!sell command appears to not be working

### ISSUE THREAD

**Issue by Milkyway12345q161** [TF2Autobot/tf2autobot#530]
**Describe the bug**

  The command !sell does not work even though the bot has enough pure to buy the item in question.

**To Reproduce**

1. Add the bot.
2. Open text chat
3. Try selling any item in his pricelist or not in his.

**Expected behavior**

  The bot should process the offer after the command is sent or in his default return a : We are not buying this item ' type of message.

**Screenshots and logs**

 https://prnt.sc/10zcvr7

**Additional context**

  Bot has more than enough pure to buy any of the both items he was trying to sell. Bot was online when this happened and the guy didnt write the names wrongly. I do not know if !buy command has the same issues

Version: 
3.7.5

**Comment by idinium96** [comment]
Try to restart your bot, and also, that's just a spam bot. I've already blocked them.

**Comment by idinium96** [comment]
My bot doesn't have any problem.

![image](https://user-images.githubusercontent.com/47635037/112909544-3c36b300-9124-11eb-8eab-d00c7b1ce108.png)
