### ISSUE TITLE
Option to see summaries of declined trades

### ISSUE THREAD

**Issue by RobotoLev** [TF2Autobot/tf2autobot#582]
**Is your feature request related to a problem? Please describe.**

I've started my own bot some days ago. I'm always frustrated when it declines trades, but I don't know why those trades were declined.

**Describe the feature you'd like**

I think, it may be good (especially for newbies) to have option for bot to send to Discord or Steam chat information about declined trades. It can be, for example, Discord webhook to channel where will be only summaries for not-accepted trades. And, next to it, option to disable it (then bot won't send this summaries, right how it's going now).

**Describe alternatives you've considered**

For now I have only one solution to understand why bot declined this or another trade. In this case admin needs to go to server and read logs to find information about that trade. It's may be hard in some times (for ex. when you use your phone to chat with bot).

**Got any bounty as a reward for anyone fulfills your request?**

N/A

**Additional context**

People may have problems with perfect configuration of bot and pricelist at first times. This feature will simplify debug process.

**Comment by idinium96** [comment]
Thanks for creating an issue about this. I've already created a poll on [TF2Autobot Discord server](https://discord.gg/D2GNnp7tv8) about this 3 months ago but still not implemented because it's quite a headache to do it. Maybe will be implemented together with v4 later.
