### ISSUE TITLE
Allow bots to buy X number of items for selected amount.

### ISSUE THREAD

**Issue by CrustTF2** [TF2Autobot/tf2autobot#603]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the feature you'd like**
Allowing bots to buy X number of a specific item for 1 set price.

Example: Bot pays 1 scrap for 5 cases/crates, and wont accept a lower amount of crates/cases per scrap.

**Describe alternatives you've considered**
There are no alternatives that can guarantee the requested amount.

**Got any bounty as a reward for anyone fulfills your request?**
N/A

**Additional context**
N/A

**Comment by idinium96** [comment]
Similar to #414
