### ISSUE TITLE
Chaining commands

### ISSUE THREAD

**Issue by offish** [TF2Autobot/tf2autobot#651]
Add chaining to commands (particularly add, delete, etc). Example:
!add sku=5021;6&intent=sell+!add name=Ellis' Cap&intent=bank
(+ as an example separator)

**Comment by idinium96** [comment]
Thanks for the suggestion.

**Comment by Preport** [comment]
Closing the issue since this feature was added in #692 and successfully merged in to master.

**Comment by idinium96** [comment]
> Closing the issue since this feature was added in #692 and successfully merged into master.

not as requested, but it's pretty much similar, so yeah thank you 👍
