### ISSUE TITLE
Misspelled word in documentation

### ISSUE THREAD

**Issue by EmirGuvenni** [TF2Autobot/tf2autobot#663]
Just a minor issue, "to" is misspelled.
[Here's the error](https://github.com/TF2Autobot/tf2autobot/wiki/Configure-your-options.json-file#--send-pre-accept-message--)
![asd](https://user-images.githubusercontent.com/45740926/118790544-89badb00-b89e-11eb-95e1-eef3c9c89d98.png)

**Comment by idinium96** [comment]
Fixed. Thank you. 👍

**Comment by idinium96** [comment]
Btw, let me know if you're on our Discord server.

**Comment by EmirGuvenni** [comment]
I tried to get in but the link was invalid. I don't remember which link it was. It would be great if you can give me a new one.

**Comment by idinium96** [comment]
Oh, I see. Here's the latest/valid one: https://discord.gg/4k5tmMkXjB
