### ISSUE TITLE
!sku Strange Particulate Protector not working

### ISSUE THREAD

**Issue by Nadpher** [TF2Autobot/tf2autobot#664]
**Describe the bug**
  !sku Strange Particulate Protector gives null;null as a result

**To Reproduce**
1. Type "!sku Strange Particulate Protector" in bot's chat.

[Screenshot](https://user-images.githubusercontent.com/43938395/119153099-39d04580-ba51-11eb-9f60-bd4f4c8d8c9a.png)

Version: v3.8.3

**Comment by idinium96** [comment]
Thanks for the report. 👍

**Comment by idinium96** [comment]
Fixed the module, but not the bot. It will be available once v4 is released.
https://github.com/TF2Autobot/node-tf2-schema-2/commit/b26db3435665f61e1901bc3e16afdecd9ef7074b
