### ISSUE TITLE
 Couldn't connect to socket server xhr poll error

### ISSUE THREAD

**Issue by RamMMMMMMMMMMMMMa** [TF2Autobot/tf2autobot#742]
I see my logs in my cmd says "couldn't connect to socket server xhr poll error" its keep repeating but the bot working properly when i start the bot i don't know why keep saying  "couldn't connect to socket server xhr poll error" can anyone fix this error

**Comment by idinium96** [comment]
Hello, if your Nodejs version is > 14.x, please uninstall it and install the latest LTS version (currently is 14.17.1 LTS - https://nodejs.org/en/)

But if you're running your bot on a Linux/VPS machine, try using `nvm` (Node version manager) to downgrade to the latest LTS version, or if still not fixed, you need to fresh install everything (including your machine - this is what I did to fix the issue and follow the [wiki](https://github.com/TF2Autobot/tf2autobot/wiki/Downloading-the-bot-on-Linux)).

**Comment by RamMMMMMMMMMMMMMa** [comment]
not working its still say " Couldn't connect to socket server xhr poll error {"typ
e":"TransportError","description":{"code":"ERR_CRYPTO_OPERATION_FAILED"}}

**Comment by Preport** [comment]
After some digging I've found that this error only occurs on node 15.x and up.
source: https://nodejs.org/api/errors.html#errors_err_crypto_operation_failed

So make sure you are using the latest LTS version.
