### ISSUE TITLE
Add individual item id pricing

### ISSUE THREAD

**Issue by joekiller** [TF2Autobot/tf2autobot#767]
I'd like to add a feature where you can price a specific item by its current item id.

## Inital goal is: 

Sell listing for item id.

## Stretch goal is:

Buy listing for specific id or specific asset id. Were you might have a dream item you want to buy and use the asset id. Or you have a specific listing for a individual, you can make a buy listing for that id exclusively.

## Details

**Is your feature request related to a problem? Please describe.**
Sometimes I want to specifically price an item. I cannot currently sell an item with the same sku as another as a differentiated item or price.

**Describe the feature you'd like**
Some command syntax to buy and sell by item id. Ie: `!add id=10151297782&intent=sell&sell.keys=1`

**Describe alternatives you've considered**
I asked in chat and it was indicated that this feature was absent.

**Got any bounty as a reward for anyone fulfills your request?**
Nope.

**Additional context**
Rules of the feature:

  1. Feature adds `![add|update|remove] id=<number>&[Listing settings parameters]`. 
  2. Feature adds `![buy|sell] id=<number>&[buy/sell parameters]`
  3. Any specific item pricing will supercede a sku price.

**Comment by joekiller** [comment]
I seems more realistic for now to just do the assetid because the current asset id is readily avaliable whereas the orginial id doesn't come over trades easily so it's fairly difficult to track that consistently.

**Comment by idinium96** [comment]
> I seems more realistic for now to just do the assetid because the current asset id is readily avaliable whereas the orginial id doesn't come over trades easily so it's fairly difficult to track that consistently.

Yes, also the `econItem` also does not include item's original ID, so yes need to use item's asset ID

**Comment by idinium96** [comment]
Also just a reminder, item's assetid will always change when the item is traded, apply paint, apply custom name, apply custom description, and so on.
