### ISSUE TITLE
Crafting tokens

### ISSUE THREAD

**Issue by WildWomble** [TF2Autobot/tf2autobot#812]
**Is your feature request related to a problem? Please describe.**
The only problem with crafting any token is that it requires time and a lot of clicking and choosing the right items for a specific token.

**Describe the feature you'd like**
A command such as:
`!craft <tokenType (class/slot)> <class (scout, soldier, etc)> <amount>`

**Describe alternatives you've considered**
I don't know any alternatives or any other sites that would allow this. I also don't know how to implement this kind of feature into the bot.

**Got any bounty as a reward for anyone fulfills your request?**
Up to 15 keys.

**Additional context**
None.

**Comment by idinium96** [comment]
Thank you for the suggestion.
For anyone that might be able to implement this, probably best to add a new key under `crafting` on the options.json file, which it will set to `true` when the user wants to switch to crafting token mode. This mode will prevent the bot from crafting any metals/weapons on start:
https://github.com/TF2Autobot/tf2autobot/blob/17fe7934a7915cd1bcefedfda5b89a1da502b1f0/src/classes/MyHandler/MyHandler.ts#L262-L272
and when the trade (accepted) is completed:
https://github.com/TF2Autobot/tf2autobot/blob/master/src/classes/MyHandler/MyHandler.ts#L2122-L2131

**Comment by idinium96** [comment]
Thank you :)
https://steamcommunity.com/tradeoffer/new/?partner=52862254&token=6BFJd67q
