### ISSUE TITLE
Separating the !stop command into 2 different commands

### ISSUE THREAD

**Issue by SachinVenugopalan30** [TF2Autobot/tf2autobot#843]
Splitting the !stop command into two separate commands.

**Is your feature request related to a problem? Please describe.**
A feature request.

**Describe the feature you'd like**

1) `!stop`: Suspends all trading services, removes all listings from backpack.tf, disable any incoming messages from people who are not an ADMIN, but keep the bot logged in to Steam and/or keep it in-game(TF2 or custom game or whatever). The admin can issue a `!start` command to the bot to once again start its services, such as listing items, accepting messages from other users, etc.
2) `!shutdown`: Shuts the bot down entirely, function similar to the current implementation of the !stop command. Only way to start the bot again is to log in to your VPS/Pi etc., and start the process again.

**Describe alternatives you've considered**

N/A

**Additional Comments**

This feature would be great to have in times when backpack.tf's services are down and not working, or when Steam servers are having issues and bots are unable to trade.
Once systems are back online, user can just start the bot again with a simple command.

There could be other reasons as well, you're welcome to list them down below. ;)

Cheers and have a good one!

**Comment by idinium96** [comment]
Thank you for creating an issue about this.
