### ISSUE TITLE
Wrong parameters for !rate command on documentation

### ISSUE THREAD

**Issue by rgalhos** [TF2Autobot/tf2autobot#844]
The documentation says the parameters for the `!rate` command are `%keyprice%` and `%keyrate%`, but they actually are `%keyPrices%` and `%keyRate%`

[Documentation](https://github.com/TF2Autobot/tf2autobot/wiki/Configure-your-options.json-file#--time--uptime--pure--rate-)
[Misc.ts](https://github.com/TF2Autobot/tf2autobot/blob/9694769bee908782a1f8828c1e5d436493bbcc1e/src/classes/Commands/sub-classes/Misc.ts#L66)

**Comment by idinium96** [comment]
Thank you for the report, will be fixed soon.

**Comment by idinium96** [comment]
Fixed, thank you!
