### ISSUE TITLE
Resetting Steam notifications for new items

### ISSUE THREAD

**Issue by carlosliam** [TF2Autobot/tf2autobot#871]
**Is your feature request related to a problem? Please describe.**
When I log into my bots and they have Steam notifications I always feel pressured to clear them. Often they are just new item notifications.

**Describe the feature you'd like**
I've changed my bots to automatically clear these notifications. I wanted to gauge interest in bringing this change to TF2Autobot, perhaps along with a flag in options to enable it.

**Describe alternatives you've considered**
None.

**Got any bounty as a reward for anyone fulfills your request?**
No.

**Additional context**
Commit showing the changes needed to add this feature (without having a corresponding flag in options): https://github.com/carlosliam/tf2autobot/commit/de9de6f6b898c1be7880e5328279ee3f3f982d96

**Comment by idinium96** [comment]
Thank you, didn't know that thing exists.
Feel free to open a pull request to the `development` branch.
