### ISSUE TITLE
My bot is creating buy orders for items not in the pricelist

### ISSUE THREAD

**Issue by Valde575** [TF2Autobot/tf2autobot#890]
My bot recently just added 5 buy orders for the following items: Strange Professional Killstreak Direct Hit, Mega Strike Taunt: The Killer Solo, Skill Gotten Gains Taunt: Square Dance, Skill Gotten Gains Taunt: Rock, Paper, Scissors, Good-Hearted Goodies Taunt: The Killer Solo. 

None of the items above are in the pricelist. 

I don't know how to reproduce the behaviour, because i have no idea how the bug happened. 

I expect the bot to only create buy orders for items in the pricelist. 

This has happened a few times before. A backpack.tf admin contacted me a week ago about this issue. He said i'd recieve a ban if this kept happening. 
![qt3i4jti3](https://user-images.githubusercontent.com/71210388/134810856-e01bf938-7a15-4cec-ac64-f4c3f5839ed2.PNG)

Version: v4.4.7.

**Comment by idinium96** [comment]
Are you sure about that? The bot should never add something by itself.

**Comment by Valde575** [comment]
I don't know how the listings got added, maybe my api key got revealed to somebody?

**Comment by idinium96** [comment]
Sorry for the very long delay.
Probably. It's safe to revoke your Backpack.tf API key and get a new one, and also for the Access Token.

I am closing this because I do believe the bot is not instructed to do such a thing.
