### ISSUE TITLE
Error: STEAM_ACCOUNT_NAME must be set in the environment

### ISSUE THREAD

**Issue by HoraceHorsecollar** [TF2Autobot/tf2autobot#893]
Hello. I'm trying to create a TF2 trading bot following the tf2autobot instructions but I keep getting this message every time I try to start up the bot.

$ node dist/app.js
C:\Users\snowd\OneDrive\Desktop\Trading Bot\tf2autobot\dist\classes\Options.js:1
215
        throw new Error('STEAM_ACCOUNT_NAME must be set in the environment');
        ^

Error: STEAM_ACCOUNT_NAME must be set in the environment
    at Object.loadOptions (C:\Users\snowd\OneDrive\Desktop\Trading Bot\tf2autobo
t\dist\classes\Options.js:1215:15)
    at Object.<anonymous> (C:\Users\snowd\OneDrive\Desktop\Trading Bot\tf2autobo
t\dist\app.js:45:27)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js
:76:12)
    at internal/main/run_main_module.js:17:47

![image](https://user-images.githubusercontent.com/91725754/135593002-8ac93fa7-f875-4939-acad-3c06a60ed55d.png)

I most certainly added my steam bot username exactly as it is spelled in the .env file where it says STEAM_ACCOUNT_NAME, so I have no idea what else it could be. I also noticed that a lot of the java scripts are giving me syntax errors whenever I click on them out of curiosity. This is all really new to me but I'm sure I can figure it out if someone could give me some help. If someone could possibly give me a walkthrough or an explanation of how to fix the problem, I would really appreciate it. Any other details that I could provide just let me know. :)

**Comment by idinium96** [comment]
Hello, this is a common error. Kindly read the solution here: https://github.com/TF2Autobot/tf2autobot/wiki/Common-Errors#startup-errors

**Comment by idinium96** [comment]
If you need any further help, join our Discord server and ask in #help channel.
