### ISSUE TITLE
An option to disable sending "price-update" messages when the price wasn't updated at the check

### ISSUE THREAD

**Issue by RobotoLev** [TF2Autobot/tf2autobot#920]
**Is your feature request related to a problem? Please describe.**

After the last update bot started to send messages to "price-update" Discord webhook on every pricecheck (even when price didn't change).

**Describe the feature you'd like**

An option to disable sending "price-update" messages when the price wasn't updated at the check

**Describe alternatives you've considered**

No alternatives except rolling back to a previous version of tf2autobot

**Got any bounty as a reward for anyone fulfills your request?**

Huge respect from me, and maybe from someone else

**Comment by idinium96** [comment]
I don't understand the issue.

**Comment by RobotoLev** [comment]
![Screenshot](https://user-images.githubusercontent.com/37415899/142666417-fb64c3ed-c8e9-4e35-b1dc-efdcd2870668.JPG)

**Comment by idinium96** [comment]
Alright. I will not make an option, I will just make sure it's not being sent.
Thank you.
