### ISSUE TITLE
Tf2autobot failed to start properly

### ISSUE THREAD

**Issue by FrostTheMedic** [TF2Autobot/tf2autobot#959]
So uh the bot was working fine and then a few weeks ago i got this error
![image](https://user-images.githubusercontent.com/96980486/147875411-17fd80bb-299f-4034-a49c-17a749c603c6.png)

**Comment by Preport** [comment]
Update your bot

2 Oca 2022 Paz 15:26 tarihinde FrostTheMedic ***@***.***>
şunu yazdı:

**Comment by FrostTheMedic** [comment]
oh alright it worked thanks
