### ISSUE TITLE
Option to enable/disable individual classified listing on backpackt.tf

### ISSUE THREAD

**Issue by TwistyTea** [TF2Autobot/tf2autobot#992]
**Is your feature request related to a problem? Please describe.**

Yes, currently I am trying to buy skins and since there are many variants for single skin, its difficult to create buy orders for each and every variant. 
**Describe the feature you'd like**

Add a new parameter in pricelist called 'listed', enabled by default but if disabled, it will not create listing on bptf.

**Describe alternatives you've considered**

Currently the bot only accepts invalid items if its an overpay and it doesn't even counter offer in case of wrong amount.
Create an option which when enabled makes the bot counter offer invalid items or 
make a whitelist and the bot will only counter offer invalid items if the sku is present in the whitelist.
Incase the bot isn't able to counter offer, decline the offer or send it for review.

**Got any bounty as a reward for anyone fulfills your request?**

Bounty: 10 keys
Discord: dzaster#7800

**Additional context**

If this is already possible, feel free to close this issue and help me

**Comment by idinium96** [comment]
Thank you for the suggestion. I might implement this feature once #995 is resolved.

**Comment by idinium96** [comment]
Hello, sorry for the long wait.
The `listed` parameter seems to be unnecessary since you are already able to disable listings with `!remove sku=<itemSku>`, or `!update sku=<itemSku>&enabled=false` commands.

Also, your alternative is completely out of topic. Please create a new issue for that.

**Comment by TwistyTea** [comment]
For some reason I didn't think of crossing the listing slot limit. Closing this now
