### ISSUE TITLE
Update `@tf2autobot/bptf-listings` to use the latest endpoints

### ISSUE THREAD

**Issue by idinium96** [TF2Autobot/tf2autobot#995]
Problems:
- Archived listings (listings that were created while the bot don't have enough currency) 
   - are not getting updated when the price changes (outdated when it's live).
   - are not getting removed on shutdown, or on the `!refreshlist` command.
- Rate limits on creating listings, etc.

**Comment by idinium96** [comment]
Thank you @arik123.
Please also check whether we need to update the [`_parseAttributes()`](https://github.com/TF2Autobot/node-bptf-listings/blob/master/classes/listing.js#L563) function (since the response might be different), and the others. You can make big changes if necessary, I don't mind.

**Comment by joekiller** [comment]
Is this issue related to messages like the folowing?

>  Error on create listings: Too Many Requests {"statusCode":429,"body":{"message":"Request limit exceeded: this endpoint only allows 15 calls per 60 seconds per user account. Try again in 14 seconds."},"attempts":6}

**Comment by arik123** [comment]
For archived listings - we need to use `deleteAllListings` Method instead of deleting listings one by one and deleting archived listings should be already handled by that function https://github.com/TF2Autobot/tf2autobot/blob/master/src/classes/Listings.ts#L476-L499

**Comment by idinium96** [comment]
> For archived listings - we need to use `deleteAllListings` Method instead of deleting listings one by one and deleting archived listings should be already handled by that function https://github.com/TF2Autobot/tf2autobot/blob/master/src/classes/Listings.ts#L476-L499

Hhhmmm... This won't help with "are not getting updated when the price changes (outdated when it's live)."
and so does for this:
https://github.com/TF2Autobot/tf2autobot/blob/d6318b6430b8d43772b768c64090645b24aa0cd6/src/classes/MyHandler/MyHandler.ts#L538-L704

**Comment by idinium96** [comment]
[KillstreakKit-Unusualifier-Strangifier-Fabricator-ChemistrySet.txt](https://github.com/TF2Autobot/tf2autobot/files/8089655/KillstreakKit-Unusualifier-Strangifier-Fabricator-ChemistrySet.txt)
